"""cbct volumes, ai pipeline runs, collaboration and planning

Revision ID: e8d7a203fb98
Revises: 548d0094649a
Create Date: 2026-07-29 22:12:59.115950
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e8d7a203fb98"
down_revision: str | None = "548d0094649a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("public_id", sa.String(length=26), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("resource_type", sa.String(length=24), nullable=False),
        sa.Column("resource_id", sa.String(length=26), nullable=False),
        sa.Column(
            "triggered_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("pipeline_name", sa.String(length=64), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="studystatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("total_ms", sa.Integer(), nullable=False),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("stages", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_id"],
            ["users.id"],
            name=op.f("fk_ai_runs_triggered_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    with op.batch_alter_table("ai_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_ai_runs_organization_id_created_at", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ai_runs_public_id"), ["public_id"], unique=True)
        batch_op.create_index(
            "ix_ai_runs_resource_type_resource_id", ["resource_type", "resource_id"], unique=False
        )

    op.create_table(
        "case_entries",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("public_id", sa.String(length=26), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("diagnosis", sa.Text(), nullable=False),
        sa.Column("treatment", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("finding_keys", sa.String(length=512), nullable=False),
        sa.Column("tags", sa.String(length=255), nullable=False),
        sa.Column("search_text", sa.String(length=1024), nullable=False),
        sa.Column("study_public_id", sa.String(length=26), nullable=True),
        sa.Column("volume_public_id", sa.String(length=26), nullable=True),
        sa.Column(
            "patient_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_case_entries_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_case_entries_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_case_entries_patient_id_patients"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_case_entries")),
    )
    with op.batch_alter_table("case_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_case_entries_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_case_entries_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_case_entries_organization_id_search_text",
            ["organization_id", "search_text"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_case_entries_public_id"), ["public_id"], unique=True)

    op.create_table(
        "comments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("author_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("resource_type", sa.String(length=24), nullable=False),
        sa.Column("resource_id", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "resolved_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_comments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
            name=op.f("fk_comments_resolved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_comments_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_comments_resource_type_resource_id", ["resource_type", "resource_id"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "ANALYSIS_COMPLETED",
                "ANALYSIS_FAILED",
                "UPLOAD_RECEIVED",
                "REPORT_READY",
                "CRITICAL_FINDING",
                "REVIEW_ASSIGNED",
                "COMMENT_ADDED",
                "FOLLOW_UP_DUE",
                name="notificationkind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "tone",
            sa.Enum(
                "POSITIVE",
                "INFO",
                "WARNING",
                "CRITICAL",
                name="notificationtone",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("href", sa.String(length=255), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_notifications_user_id_created_at", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_notifications_user_id_read_at", ["user_id", "read_at"], unique=False
        )

    op.create_table(
        "patient_notes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "patient_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("author_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "CLINICAL",
                "ADMINISTRATIVE",
                "FOLLOW_UP",
                name="notekind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_patient_notes_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_patient_notes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_patient_notes_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patient_notes")),
    )
    with op.batch_alter_table("patient_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patient_notes_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_patient_notes_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_patient_notes_patient_id_created_at", ["patient_id", "created_at"], unique=False
        )

    op.create_table(
        "review_assignments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("resource_type", sa.String(length=24), nullable=False),
        sa.Column("resource_id", sa.String(length=32), nullable=False),
        sa.Column(
            "assignee_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "assigned_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "COMPLETED",
                "DECLINED",
                name="assignmentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
            name=op.f("fk_review_assignments_assigned_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_review_assignments_assignee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_review_assignments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_assignments")),
    )
    with op.batch_alter_table("review_assignments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_assignments_assignee_id_status", ["assignee_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_review_assignments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_review_assignments_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "volumes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("public_id", sa.String(length=26), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "patient_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "uploaded_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column(
            "source_format",
            sa.Enum("DICOM", "NIFTI", name="volumeformat", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("spacing_x", sa.Float(), nullable=False),
        sa.Column("spacing_y", sa.Float(), nullable=False),
        sa.Column("spacing_z", sa.Float(), nullable=False),
        sa.Column("hu_slope", sa.Float(), nullable=False),
        sa.Column("hu_intercept", sa.Float(), nullable=False),
        sa.Column("window_center", sa.Float(), nullable=False),
        sa.Column("window_width", sa.Float(), nullable=False),
        sa.Column("source_slice_count", sa.Integer(), nullable=False),
        sa.Column(
            "field_of_view",
            sa.Enum(
                "FULL_HEAD",
                "BOTH_JAWS",
                "MAXILLA",
                "MANDIBLE",
                "TMJ",
                "SINUS",
                "IMPLANT_SITE",
                name="volumefieldofview",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("captured_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="studystatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), nullable=True),
        sa.Column("analysis_ms", sa.Integer(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_volumes_volume_positive_size")),
        sa.CheckConstraint(
            "spacing_x > 0 AND spacing_y > 0 AND spacing_z > 0",
            name=op.f("ck_volumes_volume_positive_spacing"),
        ),
        sa.CheckConstraint(
            "width > 0 AND height > 0 AND depth > 0",
            name=op.f("ck_volumes_volume_positive_dimensions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_volumes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_volumes_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_volumes_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volumes")),
    )
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_volumes_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_volumes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_volumes_organization_id_created_at", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_volumes_organization_id_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_volumes_patient_id_created_at", ["patient_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_volumes_public_id"), ["public_id"], unique=True)

    op.create_table(
        "assistant_threads",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("public_id", sa.String(length=26), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "patient_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("volume_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("study_public_id", sa.String(length=26), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_assistant_threads_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_assistant_threads_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_assistant_threads_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"],
            ["volumes.id"],
            name=op.f("fk_assistant_threads_volume_id_volumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_threads")),
    )
    with op.batch_alter_table("assistant_threads", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assistant_threads_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_assistant_threads_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_assistant_threads_public_id"), ["public_id"], unique=True
        )
        batch_op.create_index(
            "ix_assistant_threads_user_id_created_at", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "measurements",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "volume_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "DISTANCE", "ANGLE", "DENSITY", name="measurementkind", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "plane",
            sa.Enum(
                "AXIAL",
                "CORONAL",
                "SAGITTAL",
                "VOLUME",
                name="viewplane",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("points", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=8), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("value >= 0.0", name=op.f("ck_measurements_measurement_non_negative")),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_measurements_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_measurements_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"],
            ["volumes.id"],
            name=op.f("fk_measurements_volume_id_volumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurements")),
    )
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_measurements_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_measurements_volume_id_created_at", ["volume_id", "created_at"], unique=False
        )

    op.create_table(
        "volume_findings",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "volume_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("class_key", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("z", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("depth", sa.Float(), nullable=False),
        sa.Column("region", sa.String(length=32), nullable=False),
        sa.Column("tooth_number", sa.Integer(), nullable=True),
        sa.Column("tooth_confirmed", sa.Boolean(), nullable=False),
        sa.Column("extent_mm", sa.Float(), nullable=True),
        sa.Column("mean_density", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("next_steps", sa.Text(), nullable=False),
        sa.Column("produced_by", sa.String(length=48), nullable=False),
        sa.Column(
            "review",
            sa.Enum(
                "UNREVIEWED",
                "CONFIRMED",
                "REJECTED",
                name="findingreview",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "reviewed_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_volume_findings_volume_finding_confidence_range"),
        ),
        sa.CheckConstraint(
            "tooth_number IS NULL OR (tooth_number / 10 BETWEEN 1 AND 4 AND tooth_number % 10 BETWEEN 1 AND 8)",
            name=op.f("ck_volume_findings_volume_finding_tooth_number_fdi"),
        ),
        sa.CheckConstraint(
            "x >= 0.0 AND y >= 0.0 AND z >= 0.0 AND width > 0.0 AND height > 0.0 AND depth > 0.0 AND x + width <= 1.0001 AND y + height <= 1.0001 AND z + depth <= 1.0001",
            name=op.f("ck_volume_findings_volume_finding_box_within_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_volume_findings_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"],
            ["volumes.id"],
            name=op.f("fk_volume_findings_volume_id_volumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volume_findings")),
    )
    with op.batch_alter_table("volume_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_volume_findings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_volume_findings_volume_id_class_key", ["volume_id", "class_key"], unique=False
        )
        batch_op.create_index(
            "ix_volume_findings_volume_id_confidence", ["volume_id", "confidence"], unique=False
        )

    op.create_table(
        "annotations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("volume_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("study_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "MARKER", "REGION", "QUESTION", name="annotationkind", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column(
            "plane",
            sa.Enum(
                "AXIAL",
                "CORONAL",
                "SAGITTAL",
                "VOLUME",
                name="viewplane",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("z", sa.Float(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "volume_finding_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(volume_id IS NOT NULL) <> (study_id IS NOT NULL)",
            name=op.f("ck_annotations_annotation_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_annotations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_annotations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_annotations_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["volume_finding_id"],
            ["volume_findings.id"],
            name=op.f("fk_annotations_volume_finding_id_volume_findings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["volume_id"],
            ["volumes.id"],
            name=op.f("fk_annotations_volume_id_volumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotations")),
    )
    with op.batch_alter_table("annotations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_annotations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_annotations_study_id_created_at", ["study_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_annotations_volume_id_created_at", ["volume_id", "created_at"], unique=False
        )

    op.create_table(
        "assistant_messages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "thread_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", name="assistantrole", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("intent", sa.String(length=48), nullable=True),
        sa.Column("citations", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["assistant_threads.id"],
            name=op.f("fk_assistant_messages_thread_id_assistant_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_messages")),
    )
    with op.batch_alter_table("assistant_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assistant_messages_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_assistant_messages_thread_id_id", ["thread_id", "id"], unique=False
        )

    op.create_table(
        "treatment_options",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("plan_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column(
            "approach",
            sa.Enum(
                "CONSERVATIVE",
                "STANDARD",
                "COMPREHENSIVE",
                name="treatmentapproach",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column(
            "complexity",
            sa.Enum(
                "SIMPLE",
                "MODERATE",
                "COMPLEX",
                "ADVANCED",
                name="plancomplexity",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("estimated_visits", sa.Integer(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("estimated_weeks", sa.Integer(), nullable=False),
        sa.Column("benefits", sa.Text(), nullable=False),
        sa.Column("risks", sa.Text(), nullable=False),
        sa.Column("procedure_codes", sa.String(length=512), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_visits > 0", name=op.f("ck_treatment_options_option_positive_visits")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["treatment_plans.id"],
            name=op.f("fk_treatment_options_plan_id_treatment_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treatment_options")),
    )
    with op.batch_alter_table("treatment_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_treatment_options_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_treatment_options_plan_id_position", ["plan_id", "position"], unique=False
        )

    op.create_table(
        "appointments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "patient_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "created_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "plan_item_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED",
                "CONFIRMED",
                "COMPLETED",
                "CANCELLED",
                "NO_SHOW",
                name="appointmentstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_minutes > 0", name=op.f("ck_appointments_appointment_positive_duration")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_appointments_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_appointments_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_appointments_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_item_id"],
            ["treatment_plan_items.id"],
            name=op.f("fk_appointments_plan_item_id_treatment_plan_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_appointments_organization_id_starts_at",
            ["organization_id", "starts_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_appointments_patient_id_starts_at", ["patient_id", "starts_at"], unique=False
        )

    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.alter_column(
            "tooth_confirmed",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("treatment_plans", schema=None) as batch_op:
        # Every plan that already exists was assembled by a clinician, so the
        # backfill value is the honest one. The default is dropped immediately
        # afterwards to keep the column matching the model, which sets it in
        # Python rather than in the schema.
        batch_op.add_column(
            sa.Column(
                "origin",
                sa.Enum("MANUAL", "GENERATED", name="planorigin", native_enum=False, length=12),
                nullable=False,
                server_default="MANUAL",
            )
        )
        batch_op.add_column(
            sa.Column(
                "complexity",
                sa.Enum(
                    "SIMPLE",
                    "MODERATE",
                    "COMPLEX",
                    "ADVANCED",
                    name="plancomplexity",
                    native_enum=False,
                    length=12,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("estimated_weeks", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("risks", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("follow_up", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("rationale", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "source_volume_id",
                sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("source_study_public_id", sa.String(length=26), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_treatment_plans_source_volume_id_volumes"),
            "volumes",
            ["source_volume_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("treatment_plans", schema=None) as batch_op:
        batch_op.alter_column("origin", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("treatment_plans", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_treatment_plans_source_volume_id_volumes"), type_="foreignkey"
        )
        batch_op.drop_column("source_study_public_id")
        batch_op.drop_column("source_volume_id")
        batch_op.drop_column("rationale")
        batch_op.drop_column("follow_up")
        batch_op.drop_column("risks")
        batch_op.drop_column("estimated_weeks")
        batch_op.drop_column("complexity")
        batch_op.drop_column("origin")

    with op.batch_alter_table("findings", schema=None) as batch_op:
        # `sa.false()`, not `sa.text("0")`: the literal renders as `0`, which
        # SQLite accepts for a boolean and Postgres rejects outright. This
        # restores the default exactly as 548d0094649a set it.
        batch_op.alter_column(
            "tooth_confirmed",
            existing_type=sa.BOOLEAN(),
            server_default=sa.false(),
            existing_nullable=False,
        )

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index("ix_appointments_patient_id_starts_at")
        batch_op.drop_index("ix_appointments_organization_id_starts_at")
        batch_op.drop_index(batch_op.f("ix_appointments_created_at"))

    op.drop_table("appointments")
    with op.batch_alter_table("treatment_options", schema=None) as batch_op:
        batch_op.drop_index("ix_treatment_options_plan_id_position")
        batch_op.drop_index(batch_op.f("ix_treatment_options_created_at"))

    op.drop_table("treatment_options")
    with op.batch_alter_table("assistant_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_assistant_messages_thread_id_id")
        batch_op.drop_index(batch_op.f("ix_assistant_messages_created_at"))

    op.drop_table("assistant_messages")
    with op.batch_alter_table("annotations", schema=None) as batch_op:
        batch_op.drop_index("ix_annotations_volume_id_created_at")
        batch_op.drop_index("ix_annotations_study_id_created_at")
        batch_op.drop_index(batch_op.f("ix_annotations_created_at"))

    op.drop_table("annotations")
    with op.batch_alter_table("volume_findings", schema=None) as batch_op:
        batch_op.drop_index("ix_volume_findings_volume_id_confidence")
        batch_op.drop_index("ix_volume_findings_volume_id_class_key")
        batch_op.drop_index(batch_op.f("ix_volume_findings_created_at"))

    op.drop_table("volume_findings")
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.drop_index("ix_measurements_volume_id_created_at")
        batch_op.drop_index(batch_op.f("ix_measurements_created_at"))

    op.drop_table("measurements")
    with op.batch_alter_table("assistant_threads", schema=None) as batch_op:
        batch_op.drop_index("ix_assistant_threads_user_id_created_at")
        batch_op.drop_index(batch_op.f("ix_assistant_threads_public_id"))
        batch_op.drop_index("ix_assistant_threads_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_assistant_threads_created_at"))

    op.drop_table("assistant_threads")
    with op.batch_alter_table("volumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volumes_public_id"))
        batch_op.drop_index("ix_volumes_patient_id_created_at")
        batch_op.drop_index("ix_volumes_organization_id_status")
        batch_op.drop_index("ix_volumes_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_volumes_created_at"))
        batch_op.drop_index(batch_op.f("ix_volumes_content_hash"))

    op.drop_table("volumes")
    with op.batch_alter_table("review_assignments", schema=None) as batch_op:
        batch_op.drop_index("ix_review_assignments_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_review_assignments_created_at"))
        batch_op.drop_index("ix_review_assignments_assignee_id_status")

    op.drop_table("review_assignments")
    with op.batch_alter_table("patient_notes", schema=None) as batch_op:
        batch_op.drop_index("ix_patient_notes_patient_id_created_at")
        batch_op.drop_index("ix_patient_notes_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_patient_notes_created_at"))

    op.drop_table("patient_notes")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_id_read_at")
        batch_op.drop_index("ix_notifications_user_id_created_at")
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index("ix_comments_resource_type_resource_id")
        batch_op.drop_index("ix_comments_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_comments_created_at"))

    op.drop_table("comments")
    with op.batch_alter_table("case_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_case_entries_public_id"))
        batch_op.drop_index("ix_case_entries_organization_id_search_text")
        batch_op.drop_index("ix_case_entries_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_case_entries_created_at"))

    op.drop_table("case_entries")
    with op.batch_alter_table("ai_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_ai_runs_resource_type_resource_id")
        batch_op.drop_index(batch_op.f("ix_ai_runs_public_id"))
        batch_op.drop_index("ix_ai_runs_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_ai_runs_created_at"))

    op.drop_table("ai_runs")
    # ### end Alembic commands ###
