"""initial schema

Revision ID: fc22bc402903
Revises:
Create Date: 2026-07-28 14:32:40.619576
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fc22bc402903"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("actor_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(
            "ix_audit_events_actor_id_created_at", ["actor_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_audit_events_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organizations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_organizations_slug"), ["slug"], unique=True)

    op.create_table(
        "patients",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("medical_record_number", sa.String(length=64), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "sex",
            sa.Enum("MALE", "FEMALE", "UNSPECIFIED", name="sex", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("search_text", sa.String(length=560), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_patients_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
        sa.UniqueConstraint("organization_id", "medical_record_number", name="uq_patients_org_mrn"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patients_archived_at"), ["archived_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_patients_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_patients_organization_id_created_at",
            ["organization_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_patients_organization_id_full_name", ["organization_id", "full_name"], unique=False
        )
        batch_op.create_index(
            "ix_patients_organization_id_search_text",
            ["organization_id", "search_text"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_patients_phone"), ["phone"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "DENTIST", "ASSISTANT", name="userrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_users_organization_id"), ["organization_id"], unique=False
        )
        batch_op.create_index(
            "ix_users_organization_id_role", ["organization_id", "role"], unique=False
        )

    op.create_table(
        "studies",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("public_id", sa.String(length=26), nullable=False),
        sa.Column(
            "organization_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "patient_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column(
            "uploaded_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="studystatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("inference_ms", sa.Integer(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_studies_study_positive_size")),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_studies_study_positive_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_studies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_studies_patient_id_patients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_studies_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studies")),
    )
    with op.batch_alter_table("studies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_studies_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_studies_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_studies_organization_id_created_at", ["organization_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_studies_organization_id_status", ["organization_id", "status"], unique=False
        )
        batch_op.create_index(
            "ix_studies_patient_id_created_at", ["patient_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_studies_public_id"), ["public_id"], unique=True)

    op.create_table(
        "findings",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("study_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("class_key", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column(
            "review",
            sa.Enum(
                "UNREVIEWED",
                "CONFIRMED",
                "REJECTED",
                name="findingreview",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "reviewed_by_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name=op.f("ck_findings_finding_confidence_range"),
        ),
        sa.CheckConstraint(
            "x >= 0.0 AND y >= 0.0 AND width > 0.0 AND height > 0.0 AND x + width <= 1.0001 AND y + height <= 1.0001",
            name=op.f("ck_findings_finding_box_within_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_findings_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["studies.id"],
            name=op.f("fk_findings_study_id_studies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
    )
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_findings_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            "ix_findings_study_id_class_id", ["study_id", "class_id"], unique=False
        )
        batch_op.create_index(
            "ix_findings_study_id_confidence", ["study_id", "confidence"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("findings", schema=None) as batch_op:
        batch_op.drop_index("ix_findings_study_id_confidence")
        batch_op.drop_index("ix_findings_study_id_class_id")
        batch_op.drop_index(batch_op.f("ix_findings_created_at"))

    op.drop_table("findings")
    with op.batch_alter_table("studies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_studies_public_id"))
        batch_op.drop_index("ix_studies_patient_id_created_at")
        batch_op.drop_index("ix_studies_organization_id_status")
        batch_op.drop_index("ix_studies_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_studies_created_at"))
        batch_op.drop_index(batch_op.f("ix_studies_content_hash"))

    op.drop_table("studies")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_organization_id_role")
        batch_op.drop_index(batch_op.f("ix_users_organization_id"))
        batch_op.drop_index(batch_op.f("ix_users_created_at"))

    op.drop_table("users")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_phone"))
        batch_op.drop_index("ix_patients_organization_id_search_text")
        batch_op.drop_index("ix_patients_organization_id_full_name")
        batch_op.drop_index("ix_patients_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_patients_created_at"))
        batch_op.drop_index(batch_op.f("ix_patients_archived_at"))

    op.drop_table("patients")
    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizations_slug"))
        batch_op.drop_index(batch_op.f("ix_organizations_created_at"))

    op.drop_table("organizations")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_organization_id_created_at")
        batch_op.drop_index(batch_op.f("ix_audit_events_created_at"))
        batch_op.drop_index("ix_audit_events_actor_id_created_at")
        batch_op.drop_index(batch_op.f("ix_audit_events_action"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
