"""Declarative base and shared column conventions."""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import BigInteger, DateTime, Integer, MetaData, func
from sqlalchemy.engine.interfaces import Dialect
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import TypeDecorator

#: 64-bit surrogate key that still autoincrements on SQLite.
#:
#: SQLite only aliases a column to ``rowid`` — and therefore only
#: autoincrements it — when it is declared exactly ``INTEGER PRIMARY KEY``.
#: A plain ``BigInteger`` renders as ``BIGINT`` and every insert fails with
#: "NOT NULL constraint failed". The variant keeps Postgres on ``BIGINT``
#: while giving SQLite what it needs, so local development and production
#: share one set of models.
BigIntPk = BigInteger().with_variant(Integer, "sqlite")

# Explicit naming convention so Alembic emits stable, human-readable names for
# constraints instead of backend-specific autogenerated ones.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class UtcDateTime(TypeDecorator[datetime]):
    """A timestamp column that always hands Python an aware, UTC ``datetime``.

    ``DateTime(timezone=True)`` only means what it says on Postgres. SQLite has
    no native timestamp type — SQLAlchemy stores an ISO string with no offset —
    so reads come back *naive* no matter what the column declared. Pydantic
    then serialises them without a trailing ``Z``, and the same endpoint emits
    ``2026-07-06T11:46:05.985428`` on SQLite where it emits ``…Z`` on Postgres.
    Any consumer doing ``new Date(iso)`` reads the offset-less form as local
    time, silently shifting every instant by the viewer's UTC offset.

    Normalising on the way out makes the wire contract identical on both
    backends. Normalising on the way *in* closes the matching hole: SQLite
    formats a bound datetime by its wall clock and discards ``tzinfo``, so an
    aware non-UTC value would otherwise be stored as though its local reading
    were UTC. Naive binds are assumed UTC, matching :func:`utcnow`, which is
    what every writer in this codebase uses.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def utcnow() -> datetime:
    return datetime.now(UTC)


class TimestampMixin:
    """``created_at`` / ``updated_at`` maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
